version: '3'
services:
  angular-app:
    build: ./angular/benchmark
    ports:
      - "8000:8000"
      
  redis-server:
    image: 'redis'

  python-app:
    build: ./python
    depends_on: 
      - "redis-server"

  node-app:
    build: ./node
    ports:
      - "8080:8080"
    depends_on: 
      - "redis-server"
